### ISSUE TITLE
Using stringmetric in PySpark

### ISSUE THREAD

**Issue by allen-healthdirect** [MrPowers/spark-stringmetric#10]
I was able to install the spark-stringmetric:0.2.0 library to a Databaricks cluster, but all the import commands I have tried in my code throw exceptions. What is the library name I should be using in PySpark?

**Comment by MrPowers** [comment]
@allen-healthdirect - thanks for creating the issue.  Looks like [it's possible](https://stackoverflow.com/questions/36023860/how-to-use-a-scala-class-inside-pyspark) to call Scala functions in PySpark, but it only works on the driver node.  [This answer](https://stackoverflow.com/questions/31684842/calling-java-scala-function-from-a-task) has more details.  Looks like I'll need to make another library with a native PySpark implementation of these functions ;)

**Comment by allen-healthdirect** [comment]
That would be awesome!

**Comment by MrPowers** [comment]
@allen-healthdirect - I created a project called [ceja](https://github.com/mrpowers/ceja) with the PySpark native implementations of the functions in this project.  ceja is the best bet for PySpark programmers, thanks!
