### ISSUE TITLE
Add native implementations of algorithms

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-stringmetric#3]
This library is currently just a wrapper around `org.apache.commons.commons-text` functions.

Native implementations would be a lot better... Who is ready for a hard Spark coding challenge?!

@afranzi @nvander1 - take a look at the README for this project.  Want to get this on your radar 🤓

**Comment by nvander1** [comment]
Are you talking about making custom built in functions and using the Apache
commons in the custom codegen for the custom expressions? Or just
manipuliing the existing column functions to get the behavior the same as
those in Apache commons?

Le dim. 12 mai 2019 à 14:52, Matthew Powers <notifications@github.com> a
écrit :

**Comment by MrPowers** [comment]
@nvander1 - I consider `levenshtein` and `soundex` to be implemented natively.  They're both in the core Spark library in the `org.apache.spark.sql.functions` package.

I don't fully understand "making custom built in functions and using the Apache
commons in the custom codegen for the custom expressions", but I think that's what I'm looking for ;)
